### ISSUE TITLE
The absolute geometry of the Dock isn't stable

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#125]
The geometry absolute or geometry local should change on these situations:

1. when the iconSize is configured for the user.
2. if background thickness is major to the iconSize
3. the length change on normal state, eg: if the panel is running a animation the length shouldn't be update, because is unnecessary.

remember that each update for the localGeometry, change the absoluteGeometry, and then causes that visibilitymanager recalculate the hidden state and the struts. Also remember that absolute geometry just is useful for dodge windows and update the struts.

The length should be the length on normal state.
The thickness is the thickness on normal state.

Normal mean that none animation is running.

**Comment by psifidotos** [comment]
I think that this commit should fix this...

**Comment by audoban** [comment]
better.

But when I change the location and close config ui, the absolute geometry is wrong.
You also can update the absolute geometry if the user is configuring. 

steps to reproduce it

1. set always visible.
2. change the location.

**Comment by JenaPlinsky** [comment]
Yours is a great team !!! and a great example

**Comment by audoban** [comment]
I want to add a new feature but the geometry still broken, and I can't continue.
```
[debug 2:10:21.896896] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:21.952952] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:21.953953] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:21.953953] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:21.971971] [updateMaskArea:286] - update mask area:QRectF(1, 0, 68, 768)
[debug 2:10:22.8484] [unknown:0] - Couldn't find node Glass. Skipping rendering.
[debug 2:10:22.303303] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.303303] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.303303] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.304304] [updateMaskArea:286] - update mask area:QRectF(0, -15, 69, 764)
[debug 2:10:22.304304] [updateMaskArea:311] - update dock geometry:QRectF(0, -15, 69, 764)
[debug 2:10:22.336336] [unknown:0] - Couldn't find node Glass. Skipping rendering.
[debug 2:10:22.340340] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.369369] [unknown:0] - Couldn't find node Glass. Skipping rendering.
[debug 2:10:22.407407] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.487487] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.487487] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.487487] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.487487] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.488488] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 59)
[debug 2:10:22.488488] [updateMaskArea:286] - update mask area:QRectF(-7, 0, 1380, 58)
[debug 2:10:22.488488] [updateMaskArea:311] - update dock geometry:QRectF(-7, 0, 1380, 58)
[warning 2:10:22.700700] [unknown:48] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml:48:5: QML DelegateModel: Binding loop detected for property "rootIndex"
[debug 2:10:22.700700] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.700700] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[warning 2:10:22.772772] [unknown:48] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TaskWindows.qml:48:5: QML DelegateModel: Binding loop detected for property "rootIndex"
[debug 2:10:22.773773] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.773773] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.799799] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.800800] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.800800] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.800800] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:22.803803] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:23.5353] [updateMaskArea:286] - update mask area:QRectF(1, 0, 68, 768)
[debug 2:10:23.254254] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:23.254254] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:23.254254] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:23.254254] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:23.637637] [updateMaskArea:286] - update mask area:QRectF(0, -15, 69, 764)
[debug 2:10:23.670670] [updateMaskArea:286] - update mask area:QRectF(67, -15, 2, 764)
[debug 2:10:24.221221] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.221221] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.222222] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.222222] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.222222] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.222222] [updateMaskArea:286] - update mask area:QRectF(67, 0, 2, 768)
[debug 2:10:24.227227] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.521521] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.521521] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.527527] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.805805] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.805805] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.805805] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.805805] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.805805] [updateMaskArea:286] - update mask area:QRectF(0, 0, 1366, 57)
[debug 2:10:24.806806] [updateMaskArea:286] - update mask area:QRectF(67, -15, 2, 764)
[debug 2:10:24.837837] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:24.837837] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:24.838838] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:24.838838] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:26.311311] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 57)
[debug 2:10:26.311311] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 57)
[debug 2:10:26.311311] [updateMaskArea:286] - update mask area:QRectF(-8, 0, 1382, 59)
[debug 2:10:26.311311] [updateMaskArea:311] - update dock geometry:QRectF(-8, 0, 1382, 59)
```

**Comment by psifidotos** [comment]
all ok ?

**Comment by psifidotos** [comment]
I found a situation that struts were updated wrong.... I included a fix in latest master

**Comment by audoban** [comment]
it is good for now. But I'm concerned that masks are set up with negative coordinates

**Comment by psifidotos** [comment]
I can fix this in dockview setMask function and setLocalGeometry
