### ISSUE TITLE
Changing dock's location isnt robust...

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#25]
Changing dock's location from the configuration window isnt robust, there are cases that the procedure stacks in the middle...

**Comment by audoban** [comment]
Confirmed. It's the fault of DockView, please let me fix this.

**Comment by psifidotos** [comment]
yes of course...

**Comment by audoban** [comment]
I will fix this today.

**Comment by psifidotos** [comment]
of course...

**Comment by audoban** [comment]
I made many changes on DockView, please review the branch dockView before the submits the commits to master.

I found some issues concerning to localGeometry.
1. Use Always Visible, change the location and take attention to reserved area. It is very large, and is because the localdockgemetry is wrongly configured.

remember that the area reserved is configured each time that the ui update localdockgeometry.

**Comment by psifidotos** [comment]
> Use Always Visible, change the location and take attention to reserved area. It is very large, and is because the localdockgemetry is wrongly configured.

if this is because of the shadow, I have already the patch ready.... Either way I will test of course!!!

**Comment by psifidotos** [comment]
@audoban unfortunately your changes re-introduced crashes I had solved in previous commits... I will make a different commit for each crash in order to investigate them afterwards

**Comment by psifidotos** [comment]
I fixed the crashes and fixed also some minor issues, it is in master...

> Use Always Visible, change the location and take attention to reserved area. It is very large, and is because the localdockgemetry is wrongly configured.

concerning this... please be more descriptive, in my system this is a small issue concering correct timing. During the window changing location the window manager is also updated concerning the window geometry but this should happen only when the window was ended its move to the next location. In the end of this transition every has been calculated correctly.

Are we discussing the same issue?

**Comment by psifidotos** [comment]
@audoban ,  I fixed it...You were right, the localDockGeometry wasnt updated correctly in editing mode...

Nonethelesss personally I would prefer a little different behavior for this...
In editing mode the struts are updated only when the mode is changing to AlwaysVisible...
It looks more clean to the user in my opinion...

**Comment by audoban** [comment]
> unfortunately your changes re-introduced crashes I had solved in previous commits... I will make a different commit for each crash in order to investigate them afterwards

Is serius? what happen?

> Nonethelesss personally I would prefer a little different behavior for this...
In editing mode the struts are updated only when the mode is changing to AlwaysVisible...
It looks more clean to the user in my opinion...

I don't have agree. The struts would be update each time that location change, or icon size change. This is  a behavior common on plasmashell for example.

**Comment by audoban** [comment]
> concerning this... please be more descriptive, in my system this is a small issue concering correct timing. During the window changing location the window manager is also updated concerning the window geometry (for the AlwaysVisible case) but this should happen only when the window was ended its move to the next location. In the end of this transition everything has been calculated correctly.

But is possible, calculate always well the geometry local, the thickness is key for this, because its relations with icon Size, and this is constant ever during location change.

**Comment by psifidotos** [comment]
> But is possible, calculate always well the geometry local, the thickness is key for this, because its relations with icon Size, and this is constant ever during location change.

check master, this is already fixed

> I don't have agree. The struts would be update each time that location change, or icon size change. This is a behavior common on plasmashell for example.

I propose to test this behavior and then argue. Doing it plasmashell  doesnt mean is optimal for user experience. Fast way to test it in visibilitymanager.cpp:

` inline void VisibilityManagerPrivate::setDockRect(const QRect &dockRect)`
`{`
`    if (!view->containment() || this->dockRect == dockRect)`
`        return;`

replace with:

` inline void VisibilityManagerPrivate::setDockRect(const QRect &dockRect)`
`{`
`    if (!view->containment() || this->dockRect == dockRect || view->containment()->isUserConfiguring())`
`        return;`



afterwards change various locations to the dock and see on closing configuration window what happens... Much smoother and clean in my opinion

**Comment by audoban** [comment]
ok, I will try how it feel.

**Comment by psifidotos** [comment]
> Is serius? what happen?

you can check: https://github.com/psifidotos/Latte-Dock/commit/ec35e5ea58a90a34afe25dffe898fa37d919d0d7

**Comment by audoban** [comment]
ok, I take your Idea and do some modifications on visibility manager.
But the localGeometry still wrong.

1. set always visible and set location to topEdge.
2. close ui config.
3. open ui config again and change the location to leftEdge.
4. the thickness is very large.

see the audoban branch.

**Comment by audoban** [comment]
With respect to user experience, I have to accept that it feels good.

**Comment by audoban** [comment]
> ok, I take your Idea and do some modifications on visibility manager.
But the localGeometry still wrong.

false, alarm.
fixed
https://github.com/psifidotos/Latte-Dock/commit/e96765de8dba82eb2d00bc679ee8ab12bf57b87b
